### DISCUSSION TITLE
Development | Updates - 28/03/21

### DISCUSSION THREAD

**Discussion by johanjanssens** [joomlatools/joomlatools-pages#611] [Announcements]
A little update on the work done in the 4 weeks. It's been a productive few weeks with 3 pages releases and a framework release. Here is a little overview of the major improvements in both JT Pages

# Releases

Released v0.19.7, v0.19.8 and v0.19.9  with various improvements and bug fixes. More info: 

- v0.19.7: https://github.com/joomlatools/joomlatools-pages/releases/tag/v0.19.7
- v0.19.8: https://github.com/joomlatools/joomlatools-pages/releases/tag/v0.19.8
- v0.19.9: https://github.com/joomlatools/joomlatools-pages/releases/tag/v0.19.9

# Changelog 

### 1. Form redirect to external url #579

It's now possible to redirect a form to an external URL. Useful for example if the form integrates with an external webservice and you wish to redirect to it.

````yaml
---
title: Get in touch
form:
    name: contact
    schema:
        name: [string, required]
        email: [email, required]
        subject: [string, required]
        message: [string, required]
    redirect: https://www.example.com/path/to
---
````

### 2. Get page properties by path

The page `get()` and `has()` methods now allow to easily retrieve properties by path and provide interface parity between model entity, page, config and data objects.   In short you don't need to worry about the API, it works everywhere. Example:

````php
<?= page()->get('metadata/description) ?>
````

### 3. Support data:// everywhere in frontmatter #560

It was already possible to reference data values in page frontmatter property values. It's now possible to reference data objects anywhere in your frontmatter in both pages and layouts, even in deeply nested values.

For example:

````yaml
---
route: news/[digit:page]?
collection:
    model: ext:joomla.model.articles
    state:
        limit: 12
        published: 1
        category: data://config/content[catid_news]
---
````

### 4. Improvements to model hash granularity #569

Model hashes are what makes the Pages cache smart. The hash is used to calculate if a page is still valid or need to be regenerated. I have done a lot of work to make model hashes more granular.

As a result pages became faster, if content changes pages will be able to know more specifically what pages need to be regenerated and which not. Less cache regeneration === faster site. 

For a complete overview of the Model API changes please check the PR: https://github.com/joomlatools/joomlatools-pages/pull/569

### 5. Automatic link prefetching #587

The link prefetcher is a key to providing a near SPA (single page app) experience. It handles loading of pages in the background.  I have refactored the prefetcher to make it available by default. It is is now automatically injected in the page if following conditions apply:

- The page format is html
- The page is cacheable
- Static caching is enabled

It's possible to force-enable or force-disable the link prefetcher through the new` process/prefetch` attribute that is available in both page and layout frontmatter. This makes it possible to enable/disable, configure or override the prefetcher per page, or layout.

````yaml
---
process:
    prefetch: true
---
````

### 6. Allow calling template functions directly #607

For developers creating custom template helpers and filters, I have made it easier to call template functions.  Calls to template functions are now forwarding in helpers and filters. Instead of doing `$this->getTemplate()->[function]`it's now possible to call the function directly as `$this->[function]`
