### DISCUSSION TITLE
Form redirect not working

### DISCUSSION THREAD

**Discussion by raramuridesign** [joomlatools/joomlatools-pages#759] [General]
I have created a form - displays well and is a carbon copy from the example apart from some changes to the fields.

It throws this error

```
Cannot redirect to an empty URL.
.../libraries/joomlatools/library/controller/response/response.php:149
144                 throw new UnexpectedValueException(
145                     'The Response location must be a string or object implementing __toString(), "'.gettype($location).'" given.'
146                 );
147             }
148         }
149         else throw new InvalidArgumentException('Cannot redirect to an empty URL.');
150 
151         //Add the message
152         if(!empty($message)) {
153            $this->addMessage($message, $type);
154         }
```

The info at the top of the form is this

```yaml
---
title: Contact Us
summary: Contact
form:
    name: form
    processors:
        - csv
        - 'email':
            recipients: xx@xx.com
            title: The title of the form
            subject: The subject of the form
    schema:
        name: [string, required]
        email: [email, required]
        message: [string, required]
    redirect: supporters
    honeypot: name_407d3z05
---
```

the redirect page exists however I cannot work out why this throws an error.
Guidance would be appreciated.
Matthew

**Comment by johanjanssens** [comment]
Change to 

```yaml
---
title: Contact Us
summary: Contact
form:
    name: form
    processors:
        - csv
        - 'email':
            recipients: xx@xx.com
            title: The title of the form
            subject: The subject of the form
    schema:
        name: [string, required]
        email: [email, required]
        message: [string, required]
    redirect: /supporters
---
```

### Redirect

The `redirect` needs to be a valid absolute path to a page, since 0.21, all page paths needs to be absolute url's, this means `/supporters` and not `supporters`

See also: https://github.com/joomlatools/joomlatools-pages/discussions/738#breaking list of breaking changes with info what needs to be changed. Any page path needs to start with `/`.

### Honeypot

Also, you can remove the `honyepot` (unless you want to specialise it) in the frontmatter, pages handles that out of the box now. See: https://github.com/joomlatools/joomlatools-pages/pull/433
