### DISCUSSION TITLE
How to use a specific template style for a page?

### DISCUSSION THREAD

**Discussion by rbare1** [joomlatools/joomlatools-pages#867] [Q&A] [answered]
I'm using a normal Joomla site for almost all of my content, but I want to create a page with content received from an external `.md` file. In order to do this, I've created a page using this tool that fetches and renders the content. My site has a single template and that template has two template styles. The page is currently rendering with the default template style. Is there a way to use an existing non-default template style in a Page?

**Comment by johanjanssens** [comment, marked as answer]
Glad to hear you been able to get started. Please check: https://github.com/joomlatools/joomlatools-pages/pull/269  I haven't tested this with template styles, but you should be able to do:


````yaml
---
process:
    template: 
        name: [ ... ]
        config:
            templatestyle: [...]
---
````

Where [ ... ] is replaced with the name of the template and the name of the style.

Please note that this feature requires to have the Joomla extension for Pages installed. More info how to install Pages extensions please see the 0.21 release announcement: https://github.com/joomlatools/joomlatools-pages/discussions/738

You can find the code that handles the template and config here: [/v0.22.3/contrib/extensions/joomla/event/subscriber/dispatcher.php#L86](https://github.com/joomlatools/joomlatools-pages/blob/v0.22.3/contrib/extensions/joomla/event/subscriber/dispatcher.php#L86)

**Reply by rbare1** [reply]
That wasn't working for me, so I made a copy of my template to see if the frontmatter was affecting it at all. Setting the template in the frontmatter doesn't seem to work for me with or without a templatestyle. It still uses the default template.
```
---
process:
    template: 
        name: atomiccopy
        config:
            templatestyle: atomiccopydefault
---
```

My JoomlaTools Framework version is 3.4.11, so it should meet the requirements mentioned in that PR. I was able to change the page title through the frontmatter, so other parts of the frontmatter are working.

**Reply by johanjanssens** [reply]
Pages uses a later version of Joomlatools Framework. This shouldn't be the problem in this case, but important to know. It means you have installed a Joomlatools extension after you installed Pages on the site.  The new 4.x versions of our extensions will use the same framework version as Pages, which will bring everything in sync.

**Comment by desbear** [comment]
I have the same problem. I use below setting in templates/layout/default.html.php

```yaml
---
process:
   template: 
        name: monday
   filters:
       [ext:joomla.template.filter.module]
---
```
Using Joomltools Framework version is 3.5.7.
