### DISCUSSION TITLE
Joomla content plugins in page and problem with module params for flexicontent

### DISCUSSION THREAD

**Discussion by desbear** [joomlatools/joomlatools-pages#884] [Q&A] [answered]
I add  
```yaml
process:
   filters:
       [ext:joomla.template.filter.module.plugins]
 ```
       
and want to use regularlabs moduleanywhere in page. but after I add plugins to the filters. My page always show error 0.

Originally, I tried to refer to the flexicontent module by bringing the parameters in the params of the `ktml:module`of the page, but an error would occur as long as the params were brought in.

```html
<ktml:module name="flexicontent" params="<?= json(["layout" => "mod22-userstory-items",  "count" => 5, "count_feat" => 0, "method_tags" => "3",  "tag_ids" => ["15", "16", "322"]])?>">
```
