### ISSUE TITLE
Release 0.13.0

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-pages#168]
### 1. Form support #161

Easily implement forms in a page and store the form submissions in csv file, database, log, or a custom location.

````yaml
form:
    name: contact
    fields:
        name: [string, required]
        email: [email, required]
        subject: [string, required]
        message: [string, required]
   processors: [csv, database: {table: name}, email: {recipient: info@foo.com, title: Contact Form, subject: New submission for contact form}]
    redirect: thank-you
    honeypot: name_01234567
````

The form definition includes the form fields validation rules, form processors, page to redirect to after a successful submission,  and enables the honeypot. The Form API also offers support for POST only forms, aka form endpoints.

### 2. CSV support #160

Support for CSV files has been added for both data and collections. 

_Data_: CSV files can now be accessed through the data() template function, both locally stored files or URL"s to files that return CSV.

_Collections_: Support for a CSV format has been added to allow exposing CSV data. For example to expose a list of data add a page called data.csv' and as frontmatter use:

### 3. Refactor config handling #163

Improves the config handling by moving the bootstrapping into ComPagesConfig and exposing the site path using getSitePath() method.

A new 'headers' config option is also added that allows to defining additional http headers. This can for example be used to setup http security headers.

#### Additional config options

- headers: [array]
