### ISSUE TITLE
Release 0.18.0

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-pages#384]
### 1. Link prefetcher #285

Introduced an interaction based link `prerenderer` and a customizable and throttled in-viewport link `prefetcher` script that preloads links during idle time on fast connections.

Prefetcher can also automatically prefetch URLs for links that are in-viewport during idle time. This feature is disabled by default.

### 2. Async Http Cache Proxy #305

The http cache proxy has been refactored to support async cache validation. The proxy will return the resource from cache immediately if it exists and validate it async in the background. This approaches ensure that each request is equally fast and solves the slow revaliation resquest problem. 

### 3. Cache collection #311

Implemented a cache collection which uses the http cache as data source and further improved the cacheable behaviour to make the http cache fully transparent. Sending a cache validation request will validate and if needed regenerate the cache.

- `Cache-Control: no-cache`
- `Cache-Control: max-age=0`

For more advanced cache validation scenario's the cache can now be exposed externally, for example to build an external cache (re)generator as part of a deployment pipeline or can be used to build a sitemap.

```yaml
---
collection:
    model: cache
    state:
        limit: 0
process:
    cache: false
metadata:
    robots: [noindex]
---
```

### 4. Use Joomlatools Mason and Github actions for build scripts #37

Implemented support for Joomlatools Mason, our new Joomlatools build tool. Mason is running as a Github Action automates the build of release packages which are now also available using the  `http://files.joomlatools.com` endpoint.

### 5. Add config() template function #291

The config handling has been refactored and  a new `config()`template function added that gives easy access to both the site runtime configuration as the configuration of extensions or other objects.

`<?= config()->http_cache ?>`

### 6. Automatically set new collection states #299

Moved the logic to define new states to the collection, and makes it available to database collections too.

This allows to filter any collection, either by hardcoding a new state, or through a dynamic page route. The state name needs to be the same as the database column name.

### 7. Multiple filter constraints #301

Added support for multiple filter constraints for the same attribute

````yaml
---
collection:
    model: database?table=bar
    state:
         filter:
            foo:
                - 'gt:1'
                - 'lt:10'
---
````
URL: `http://example.com/bar?filter[id][]=gt:1&filter[id][]=lt:10`

### 8. Support relative cache time #380

Addded support for using an English textual relative datetime for all the cache lifetime settings.

````php
<?php
retur [  
    'http_cache_time' => '1hour',
    'http_resource_cache_time => '1day'',
],

````

### 9. Add X-Robots-Tag header #310

Added the `X-Robots-Tag` header for GET or HEAD requests if robots metadata is specified for the page.

### 10. Add support for shuffle to database collection #307

Added support for the shuffle ordering to the database collection.

````yaml
---
collection:
    model: database?table=content
    state:
        order: shuffle
---
````

URL: `http://example.com/bar?order=shuffle`

### 11. Improve webhook processor #335

Improved the webhook form processor `ComPagesControllerProcessorWebhook` and made it more easily extendible and configurable.

### 12. Allow to configure data root path for a webservice collection #333

```yaml
---
collection:
    model: webservice
    config: 
       url: 'example.com?format=json&x=y'
       data: ['path', 'to', 'items']
---
```

Added a new data config option to define the name or path fo the data element.

### 13. Add a default pages collection #327

`<? $pages = collection('pages'); ?>`

### Fixes

- Issue with data objects after filtering #289
- Sitemap urlset declaration #287
- theme:// alias not working in multi-site mode #382
- Template cache validation not working #293
- Throw exception if collection cannot be found #303
- Fix Travis script #350
- Joomla login no longer working #342
- Do not filter decorated component content #340
- Division by zero error when limit is 0 #338
