### ISSUE TITLE
Improve webservice collection

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-pages#478]
Allow to define custom headers for the webservice collecton. For example to easily set an Authorization header:

````yaml
---
collection:
    model: webservice
    config:
        url: http://www.example.com/api/records.json
        headers: 
            Authorization: Bearer [key]
---
```
