### ISSUE TITLE
Release v0.19.2

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-pages#494]
### 1. Cache revalidator custom header support #493

Added support for custom headers to the cache revalidator. Example: `--headers.Foo=foo --headers.Bar=bar`

### 2. Improve webservice collection #479

Added a new headers config option to easily define custom headers. For example:

```yaml
---
collection:
    model: webservice
    config:
        url: http://www.example.com/api/records.json
        headers: 
            Authorization: Bearer [key]
---
```

### 3. Do not cache statically if must-revalidate #491

A page will not be cached statically if it must be revalidated. This allows to set a global cache time for the static cache and still define a different cache time per page. 

### 4. Improve static cache config #485

Fixes

- Multiple nested filter constraints #477
- Do not list cached pages if caching is not enabled #481
- Fix notices #483
