### ISSUE TITLE
Release v0.19.11

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-pages#660]
### 1. Component decoration #659

Extended the decoration support to components. Menu item parameters are specified through the frontmatter. Pages will create a virtual menu item and handle rendering and routing of the component.

```yaml
---
route: articles/[*:component]?
process:
    decorate:
        component: content
        view: categories
---
```
Note: _Pages will not inject your page into the Joomla menu modules. This is out of scope for this PR, but is being planned._

### 2. Use Pages as Joomla template engine #654

Made it possible to use a custom Pages theme when decorating Joomla menu items with full [routing](https://github.com/joomlatools/joomlatools-pages/wiki/Routes) support.

```yaml
---
layout: index
process:
    decorate: true
---

<ktml:content>
```

### 3. Improve cache location handling #648

Improved the cache location and cache file naming making it easy to configure the default cache location for a site. This allows to move the cache outside of the site root, or to alternate the cache location for the same site, for example to setup a content staging environment for the same site.

### 4. Allow to pass filter config options in frontmatter #627

Added support for filter config options in the frontmatter. Example:

```yaml
---
layout: developper/article
process:
    filters: [toc, highlight: {selector: article, badge_lang: false}]
---
````

### 5. Exclude filters #622

Exclude filters in a child layout, or page. The filter is disabled but will still run to make sure it cleans up any tags without filtering the page content.

````markdown
---
process:
    filters: -toc
---
````

### 6. Alpine.js #642

Make the alpine.js version configurable through the helper. Default version is set at 2.8.2. To include alpine js:

```php
<?= helper('behavior.alpine', ['version' => '2.8.2']); ?>
```

### 7. Improve pagination #641

Improved the paginator markup making it semantic, accessible, and SEO optimised.

### 8. Remove anchorjs in toc filter #639

Rreplaced acnhorjs in the TOC filter with an accessible vanila css/html solution.

### 8. Template url for form redirects #637

The redirect parameter defines the location to be redirected to and can be templated using the template URI's standard. When a template uri is used the submitted form data will be used to expand the template url. For example:

```yaml
form:
   redirect: http://example.com/{id}
   schema:
        name: [string, required]
        email: [email, required]
        id: [string, required]
```

### 9. Add 'debug' config option #635

Added a new `debug` config option. By default the value reflects your Joomla debug setting unless configured otherwise.

### 10. Load assets from cdn #633

Load assets from either `unpkg.com` or from `files.joomlatools.com` and added a version config option has been added to the anchor, prefetcher and highlight behaviors to make it easy to configure the version to be used.

### 11. Add host:// alias #631

 Added a new `host://` alias that will be replaced with the authority (schema + host) of the url.

### Fixes

- Static cache is no longer working #652
- Template cache no longer working #644
- Canonical url is not correct #646
- Fix typo in entity #640
- Joomla Modern URL routing not working #625
